---
- name: Create celery user
  become: yes
  user: 
    create_home: no
    name: "celery"
    groups:
      - www-data
  tags: 
    - celery

- name: Add current user to celery and www-data groups
  become: yes
  user: 
    name: "{{ user_name }}"
    groups: 
      - celery
      - www-data
    append: yes
  tags:
    - celery

- name: Create celery log directory
  become: yes
  file: 
    path: "/var/log/celery"
    state: directory
    owner: "celery"
    group: "www-data"
    mode: 02775



- name: Copy celery config files
  become: yes
  template:
    src: "celery/{{ item }}.j2"
    dest: "/etc/default/{{ item }}"
    mode: 0644
  with_items:
    - 'celeryd'
    - 'celerybeat'
  tags: 
    - celery

- name: Copy celery service files
  become: yes
  copy:
    src: "{{ item }}.service"
    dest: "/etc/systemd/system/{{ item }}.service"
    mode: 0644
  with_items:
    - 'celeryd'
    - 'celerybeat'
  tags: 
    - celery

- name: Start celeryd
  become: yes
  ansible.builtin.service:
    name: celeryd
    daemon_reload: yes
    enabled: yes
    state: reloaded

- name: Start celerybeat
  become: yes
  ansible.builtin.service:
    name: celerybeat
    enabled: yes
    state: restarted
