- hosts: regluit-dev
  gather_facts: false
  tasks:
    # Need to install python and pip first so Ansible will function
  - name: Install python{{ python_version }} and pip
    become: true
    raw: bash -c "apt -qqy update && apt install -y python{{ python_version }}  python3-pip python3-apt"
    register: output
    changed_when: output.stdout != ""



  - name: Gathering Facts
    setup:

  - include_role: 
      name: regluit_prod
  
  