# sets "ondeck.unglue.it" to handle "unglue.it"
- hosts: regluit-ondeck
  gather_facts: false
  tasks:
    # Need to install python3.8 and pip first so Ansible will function
  - name: Install python3.8 and pip
    become: true
    raw: bash -c "apt -qqy update && apt install -qqy python3.6-dev python-pip"
    register: output
    changed_when: output.stdout != ""

  - name: Gathering Facts
    setup:

  - include_role: 
      name: regluit_prod
  
  