---
# Need to install python3.8 and pip first so Ansible will function
- name: Install python3.8 and pip for common
  become: true
  raw: bash -c "apt -qqy update && apt install -qqy python3.8-dev python3-pip"
  register: output
  changed_when: output.stdout != ""

- name: Gathering Facts
  setup:

- name: Install base regluit dependencies
  become: true
  apt:
    name: ['git', 'python-setuptools', 'python-lxml', 'build-essential', 'libssl-dev', 'libffi-dev', 'libxml2-dev', 'libxslt-dev', 'mysql-server', 'mysql-client', 'libmysqlclient-dev', 'python-mysqldb', 'libcairo2']
    update_cache: true
    state: present

- name: Install virtualenv
  pip3:
    name: "virtualenv"
    state: present

- name: Install python packages to virtualenv
  pip3:
    requirements: "{{ project_path }}/requirements.txt"
    state: present
    virtualenv: "{{ project_path }}/venv"

- name: Add project to PYTHONPATH of virtualenv
  template:
    src: "{{ item }}.j2"
    dest: "{{ project_path }}/venv/lib/python3.8/site-packages/{{ item }}"
  with_items:
    - 'regluit.pth'
    - 'opt.pth'

- name: Create keys directory
  file:
    path: "{{ project_path}}/settings/keys"
    state: directory

- name: Copy keys files
  copy:
    src: "{{ project_path }}/settings/dummy/__init__.py"
    dest: "{{ project_path }}/settings/keys/__init__.py"
    remote_src: yes

- name: Copy django settings template
  template:
    src: me.py.j2
    dest: "{{ project_path }}/settings/me.py"

- name: Copy key templates to keys directory
  template:
    src: "{{ item }}.j2"
    dest: "{{ project_path }}/settings/keys/{{ item }}"
  with_items:
    - 'common.py'
    - 'host.py'

- name: MySQL setup
  become: true
  import_tasks: mysql.yml

- name: Redis setup
  become: true
  import_tasks: redis.yml

# - name: Celery setup
#   import_tasks: celery.yml
